version: '3.5'
services:
  api:
    container_name: web-app-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web-api
    env_file:
      - config/.env
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: web-app-db
    networks:
      - web-api
    env_file:
      - config/.env
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: redis
    container_name: web-app-redis
    networks:
      - web-api
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"

volumes:
  postgres: ~
  redis: ~

networks:
  web-api:
    name: web-api-network
